targets = [{ triple = "x86_64-unknown-linux-gnu" }]

[licenses]
unlicensed = "deny"
# only allow GPL-3.0 compatible licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Unicode-DFS-2016",
    "GPL-3.0",
    "BSD-3-Clause",
]
deny = ["GPL-2.0"]
default = "deny"
confidence-threshold = 1.0
