name: "Install RPM dependencies"
description: "Install RPM dependencies"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        dnf install -y openssl-devel python3-devel sqlite-devel dnf-plugins-core util-linux gcc sudo skopeo
        dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
        dnf install -y docker-ce-cli
