name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04
    container:
      image: almalinux:9
    steps:
      - uses: ./.github/actions/dependencies
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Check format
        run: cargo fmt -- --check
      - name: Run cargo check
        run: cargo check --locked
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-24.04
    container:
      image: almalinux:9
      options: --privileged
    steps:
      - uses: ./.github/actions/dependencies
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses:  ./.github/actions/test

  cargo-deny:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2

  build:
    runs-on: ubuntu-24.04
    container:
      image: almalinux:9
    steps:
      - uses: ./.github/actions/dependencies
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-generate-rpm
        run: cargo install cargo-generate-rpm
      - name: Make oci image
        run: make oci
