name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
    contents: read

jobs:
  check:
    runs-on: ubuntu-24.04
    container:
      image: almalinux:9
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dependencies
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Check format
        run: cargo fmt -- --check
      - name: Run cargo check
        run: cargo check --locked
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-24.04
    container:
      image: almalinux:9
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dependencies
      - uses: dtolnay/rust-toolchain@stable
      # skip simple_build on almalinux - appears to be an RPM reproducibility issue
      - name: Run tests
        shell: bash
        run: |
          useradd -m -s /bin/bash rootless
          su - rootless
          cargo test --features test-docker -- --skip test_simple_build

  test-fedora:
    runs-on: ubuntu-24.04
    container:
      image: fedora:40
      options: --privileged
    steps:
      - name: Install dependencies
        run: |
          dnf install -y openssl-devel python3-devel sqlite-devel dnf-plugins-core util-linux rust cargo skopeo
          dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
          dnf install -y docker-ce-cli
      - uses: actions/checkout@v4
      - name: Run tests
        shell: bash
        run: |
          useradd -m -s /bin/bash rootless
          su - rootless
          cargo test --features test-docker

  cargo-deny:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2

  build:
    runs-on: ubuntu-24.04
    container:
      image: almalinux:9
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dependencies
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-generate-rpm
        run: cargo install cargo-generate-rpm
      - name: Make rpm
        run: make rpm
